# https://github.com/apache/superset
# Used by Superset Helm Chart as worker and client
FROM apachesuperset.docker.scarf.sh/apache/superset:4.0.0@sha256:7abdba4afa2875762bdaa51f478e7d5d5ccf0785b105f1752d09c43488a7f736
LABEL name="superset"
# renovate: datasource=docker depName=apachesuperset.docker.scarf.sh/apache/superset
LABEL dib.extra-tags="4.0.0"
