# This Dockerfile is only used to init your dib managed repository
#
# Within this repository, run the following commands
#
# $ docker build -t <your_registry_url>/dib-referential .
# $ docker push <your_registry_url>/dib-referential
#
# If you choose to use another name than `dib-referential`, you will need
# to set it in your command-line, with `--referential-image`
FROM alpine
LABEL name="dib-referential"
