# https://github.com/apache/superset
# Used by Superset Helm Chart as init container
FROM apache/superset:dockerize@sha256:afe59523a6c8774c3b16d0f44146b2e52f327a7d26a47b4cc63b904fcdedf057
LABEL name="superset-dockerize"
# renovate: datasource=docker depName=apache/superset
LABEL dib.extra-tags="dockerize"
