<script lang="ts">
	import { imagesStore } from '$stores/report.ts';
	import Accordion from '$lib/components/ui/accordion/Accordion.svelte';
</script>

<svelte:head>
	<title>Images scan logs</title>
</svelte:head>

<h1>Security scan logs (Generated by Trivy)</h1>

<div>
	{#each $imagesStore as image}
		<Accordion headerText={image.name}>
			{#if image.scan && image.scan.Results}
				{#each image.scan.Results as result}
					<table class="trivy-results">
						<caption>
							scan type: {result.Class}
						</caption>
						{#if result.Vulnerabilities}
							<thead>
								<tr>
									<th>Package</th>
									<th>Vulnerability ID</th>
									<th>Severity</th>
									<th>Installed Version</th>
									<th>Fixed Version</th>
								</tr>
							</thead>
							<tbody>
								{#each result.Vulnerabilities as vulnerabily}
									<tr>
										<th>{vulnerabily.PkgName}</th>
										<th>{vulnerabily.VulnerabilityID}</th>
										<th>{vulnerabily.Severity}</th>
										<th>{vulnerabily.InstalledVersion}</th>
										<th>{vulnerabily.FixedVersion || 'Ø'}</th>
									</tr>
								{/each}
							</tbody>
						{:else}
							<thead></thead>
							<tbody></tbody>
						{/if}
						<tfoot>
							<tr>
								<th scope="row" colspan="4">Total</th>
								<td>{result.Vulnerabilities ? result.Vulnerabilities.length : 0}</td>
							</tr>
						</tfoot>
					</table>
				{/each}
			{:else}
				{image.scan}
			{/if}
		</Accordion>
	{/each}
</div>

<style>
	.trivy-results {
		table-layout: fixed;
		width: 100%;
		border-collapse: collapse;
		border: 1px solid black;
	}

	.trivy-results tbody tr th {
		font-weight: normal;
	}

	th,
	td {
		border: 1px solid black;
		padding: 1em 2em;
	}
</style>
