<script lang="ts">
	import { imagesStore } from '$stores/report.ts';
	import Accordion from '$lib/components/ui/accordion/Accordion.svelte';
</script>

<svelte:head>
	<title>Images tests logs</title>
</svelte:head>

<h1>Images tests logs (Generated by Goss)</h1>

<div>
	{#each $imagesStore as image}
		<Accordion headerText={image.name}>
			{#if image.goss && image.goss.testcases}
				<ul>
					{#each image.goss.testcases as testcase}
						<li>
							{#if testcase.failure}
								<p class="text-warning">{testcase.name}</p>
								<pre><code class="language-plaintext">
{testcase.failure}
								</code></pre>
							{:else}
								<p class="text-success">{testcase.name}</p>
								<pre><code class="language-plaintext">
{testcase.system_out}
								</code></pre>
							{/if}
						</li>
					{/each}
				</ul>
			{:else}
				{image.goss}
			{/if}
		</Accordion>
	{/each}
</div>
