---
name: Actions security
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths: [.github/workflows/**]

permissions:
  contents: read

jobs:
  # Actions security tries to keep your GitHub actions secure by following these simple rules:
  # - Check if no issues are found on your GitHub Actions
  # - Ensure that all GitHub Actions and reusable workflow are pinned using directly a commit SHA
  actions_security:
    runs-on: ubuntu-24.04-arm
    permissions:
      security-events: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Github Actions lint
        run: |
          curl -O https://raw.githubusercontent.com/rhysd/actionlint/main/.github/actionlint-matcher.json
          echo "::add-matcher::.github/actionlint-matcher.json"
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@cc9ffdc62fadb9f83b46dd0979d9ad50408cc6a6 # v5.0.2
